name: CI
on:
  push:
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - run: nix -L flake check
      - run: ls
      - run: nix-shell -p git && git pull https://github.com/dylanaraps/neofetch
      - run: nix-shell -p bash && bash neofetch/neofetch
      - run: nix build
